Info<<"	Setting region fields... "  << endl;

volVectorField& Ai = As[i];

volScalarField& muri = murs[i];
volScalarField& mui = mus[i];
volScalarField& chii = chis[i];
volVectorField& Ji = Js[i];

volVectorField& Bi = Bs[i];
volVectorField& Bri = Brs[i];
volVectorField& Hi = Hs[i];
volVectorField& Hri = Hrs[i];
volVectorField& Mi = Ms[i];
volVectorField& MIi = MIs[i];
volVectorField& MIri = MIrs[i];
volVectorField& MTi = MTs[i];
volVectorField& MTri = MTrs[i];

volTensorField& Ti = Ts[i];
volTensorField& Tri = Trs[i];
volVectorField& Fli = Fls[i];

volVectorField& Fki = Fks[i];
volVectorField& Fkri = Fkrs[i];
volVectorField& Fk2i = Fk2s[i];
volVectorField& Fk2ri = Fk2rs[i];
